version: '2'
services:
  configserver:
    image: rgederin/config-service:dev
    ports:
       - "8888:8888"
  licensingservice:
    image: rgederin/licensing-service:dev
    ports:
      - "8080:8080"
    environment:
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"