version: '2'
services:
  eurekaserver:
    image: rgederin/eureka-service:dev
    ports:
       - "8761:8761"
  configserver:
    image: rgederin/config-service:dev
    ports:
       - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
  zuulserver:
    image: rgederin/zuul-service:dev
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
  licensingservice:
    image: rgederin/licensing-service:dev
    ports:
       - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
  organizationservice:
    image: rgederin/organization-service:dev
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
#  organizationservice2:
#    image: rgederin/organization-service:dev
#    ports:
#      - "8086:8086"
#    environment:
#      PROFILE: "default"
#      SERVER_PORT: "8085"
#      CONFIGSERVER_URI: "http://configserver:8888"
#      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#      EUREKASERVER_PORT:   "8761"
#      CONFIGSERVER_PORT:   "8888"
