spring:
  application:
    name: zuulservice
  profiles:
    active:
      default

server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  routes:
    organizationservice: /organization/**
    licensingservice: /licensing/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

licensingservice:
  ribbon:
    ReadTimeout: 15000