
####################################
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/rgederin/config-repository
          searchPaths: licensingservice

# Service discovery
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---

#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
#
#server:
#  port: 8888
#

