
####################################
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/rgederin/config-repository
          searchPaths: licensingservice
---

#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
#
#server:
#  port: 8888
#

